name: k8s-deploy-on-trigger

on:
  # Manual run from the Actions tab with a form
  workflow_dispatch:
    inputs:
      DockerImageName:
        description: "The name of the Docker image to update."
        required: true
        type: string
      BranchName:
         description: "This parameter represents the branch that triggered or should be used by the workflow."
         required: true
         type: string
      ReleaseTag:
        description: "This parameter describes the version/tag used for a release — typically applied to a Docker image or deployment artifact"
        required: true
        type: string

  # Programmatic run from API / gh / another workflow
  repository_dispatch:
    types: ["Deploy On Trigger"]

env:
  REGISTRY: ghcr.io
  BRANCH_NAME: ${{ inputs.BranchName || github.event.client_payload.BranchName }}
  IMAGE_NAME:  ${{ inputs.DockerImageName || github.event.client_payload.DockerImageName }}
  RELEASE_TAG: ${{ inputs.ReleaseTag || github.event.client_payload.ReleaseTag }}
  
  Overlay: ${{ 
   contains('develop', inputs.BranchName || github.event.client_payload.BranchName) && 'acc' ||
   contains('main', inputs.BranchName || github.event.client_payload.BranchName) && 'prd'
   }}


permissions:
  contents: write  # needed to push commits
  actions: write
  pull-requests: write
  checks: write 

jobs:
  detect:
    name: "Find all matching deployment files"
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.find.outputs.files }}
    steps:    
      - name: Validate inputs
        run: |
          if [ -z "${{ env.BRANCH_NAME }}" ]; then
            echo "BRANCH_NAME is missing"
            exit 1
          fi

          if [ -z "${{ env.IMAGE_NAME }}" ]; then
            echo "IMAGE_NAME is missing"
            exit 1
          fi

          if [ -z "${{ env.RELEASE_TAG }}" ]; then
            echo "RELEASE_TAG is missing"
            exit 1
          fi
          echo "Inputs are valid: BRANCH_NAME=${{ env.BRANCH_NAME }}, IMAGE_NAME=${{ env.IMAGE_NAME }}, RELEASE_TAG=${{ env.RELEASE_TAG }}"

      - uses: actions/checkout@v6
      - id: find
        shell: bash
        run: |
          MATCHES=$(git grep -l -F --no-index "${{ env.IMAGE_NAME }}:" -- "deployments/dlz/**/${{ env.Overlay }}/patch-deployment.yaml" || true)
          FILES=$(printf "%s\n" "$MATCHES" | jq -R -s -c 'split("\n")[:-1]')
          echo "files=$FILES" >> $GITHUB_OUTPUT

  deploy:
    name: Dispatch deploy per file
    needs: detect
    if: ${{ needs.detect.outputs.files != '[]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: |
         for file in $(echo '${{ needs.detect.outputs.files }}' | jq -r '.[]'); do
            echo "Dispatching for $file"

            gh workflow run k8s-deploy-connector.yml \
            -f FilePath="$file" \
            -f DockerImageName="${{ env.IMAGE_NAME }}" \
            -f ReleaseTag="${{ env.RELEASE_TAG }}" \
            -f Environment="tce-dip-${{ env.Overlay }}"
            
            echo "Fetching latest run..."
            
            run_id=$(gh run list \
             --workflow=k8s-deploy-connector.yml \
             --limit 1 \
             --json databaseId \
             --jq '.[0].databaseId')

           echo "Waiting for run $run_id"
           gh run watch $run_id --exit-status

         done
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
