name: k8s-deploy-on-trigger

on:
  # Manual run from the Actions tab with a form
  workflow_dispatch:
    inputs:
      DockerImageName:
        description: "The name of the Docker image to update."
        required: true
        type: string
      BranchName:
         description: "This parameter represents the branch that triggered or should be used by the workflow."
         required: true
         type: string
      ReleaseTag:
        description: "This parameter describes the version/tag used for a release — typically applied to a Docker image or deployment artifact"
        required: true
        type: string

  # Programmatic run from API / gh / another workflow
  repository_dispatch:
    types: ["Deploy On Trigger"]

env:
  REGISTRY: ghcr.io
  Environment: ${{ inputs.BranchName == 'develop' && 'acc' || inputs.BranchName == 'main' && 'prd' || inputs.BranchName }}

permissions:
  contents: write

jobs:
  detect:
    name: "Find all matching deployment files"
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.find.outputs.files }}
    steps:
      - uses: actions/checkout@v4
      - id: find
        shell: bash
        run: |
          set -euo pipefail
          MATCHES=$(git grep -l -F --no-index "${{ inputs.DockerImageName }}:" -- "deployments/dlz/**/${{ env.Environment }}/patch-deployment.yaml" || true)
          FILES=$(printf "%s\n" "$MATCHES" | jq -R -s -c 'split("\n")[:-1]')
          echo "files=$FILES" >> $GITHUB_OUTPUT
  deploy:
    name: "Deploy to Kubernetes for each matching file."
    needs: detect
    if: ${{ needs.detect.outputs.files != '[]' }}

    strategy:
      max-parallel: 1
      matrix:
        files: ${{ fromJson(needs.detect.outputs.files) }}

    runs-on: ubuntu-latest

    steps:
      - name: Trigger k8s deploy workflow
        run: |
          echo "Dispatching deploy for ${{ matrix.files }}"
          gh workflow run k8s-deploy-connector.yml \
            -f FilePath="${{ matrix.files }}" \
            -f DockerImageName="${{ inputs.DockerImageName }}" \
            -f ReleaseTag="${{ inputs.ReleaseTag }}"
